apiVersion: apps/v1
kind: Deployment
metadata:
  name: vtiproject
spec:
  replicas: 3
  selector:
    matchLabels:
      app: vtiproject
  template:
    metadata:
      labels:
        app: vtiproject
    spec:
      containers:
      - name: vtiproject
        image: heyhuy/vtiproject1:v1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
          - containerPort: 5000